---
baseURL: https://nate-geslin-dot-com.vercel.app
languageCode: en-us
title: nategeslin.com
paginate: 5
theme: PaperMod
menu:
  main:
  - url: https://nate-geslin-dot-com.vercel.app/index.xml
    name: RSS
    weight: 3
    identifier: RSS
  - url: "/posts/"
    name: Blog
    weight: 1
    identifier: Blog
outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  env: production
  description: I Lead projects and I make things
  author: Nate Geslin
  disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  profileMode:
    enabled: true
    title: Nate Geslin
    subtitle: I Lead projects and I make things
    imageUrl: https://www.fillmurray.com/425/425
    buttons:
    - name: Medium
      url: https://nategeslin.medium.com/
    - name: Github
      url: https://github.com/n8rzz
    - name: Linkedin
      url: https://www.linkedin.com/in/nate-geslin/
    socialIcons:
    - name: github
      url: https://github.com/n8rzz
    - name: gitlab
      url: https://github.com/n8rzz
    - name: rss
      url: index.xml
